### ISSUE TITLE
Questions regarding Setup instructions in README.md

### ISSUE THREAD

**Issue by lucasPDY** [rendegosling/payslip-exam#1]
Dear @renlesterdg, was trying to do the tasks but noticed a few inconsistencies in the README.md file.

Firstly, should I be cloning this repository directly with `git clone`? Or am I allowed to make a fork of this repository? The setup instructions only mentioned cloning, as seen below.
![image](https://user-images.githubusercontent.com/46293489/78590119-a9eb2e80-7884-11ea-8416-609fda1adc2f.png)

However, under the **Instructions** section of the readme, it suggests that we should be forking the repo instead, as seen below.
![image](https://user-images.githubusercontent.com/46293489/78590415-2aaa2a80-7885-11ea-8f8c-953d147faf6e.png)

Also, I noticed that the previous commit message for this task was to change the goal from forking to cloning, so I was slightly confused on what my next steps should be.

On an unrelated note, is **unit testing** required for this task?

**Comment by renlesterdg** [comment]
@lucasPDY sorry for the inconsistencies you can fork or you can create a new repo based on the latest code since the payslip exam doesnt have any code included.

For unit testing, yes
